---
Name: workflow_siteconfig_trello
After: '#workflow_siteconfig'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    SiteConfigTrelloExtension: SilverStripe\Workflow\Trello\SiteConfigTrelloExtension

---
Name: workflow_step_trello
---
SilverStripe\Workflow\Step:
  extensions:
    StepExtension: SilverStripe\Workflow\Trello\StepExtension

SilverStripe\Workflow\StepRelation:
  extensions:
    TrelloStepRelationExtension: SilverStripe\Workflow\Trello\StepRelationExtension

---
Name: workflow_widget_trello
---
SilverStripe\Workflow\WorkflowWidget:
  extensions:
    WorkflowWidgetExtension: SilverStripe\Workflow\Trello\WorkflowWidgetExtension

---
Name: workflow_controller_trello
---
SilverStripe\Workflow\WorkflowController:
  extensions:
    WorkflowControllerExtension: SilverStripe\Workflow\Trello\WorkflowControllerExtension
